/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-dim": "#843a00",
        "secondary-dim": "#004e9d",
        "surface-container-low": "#eff1f2",
        "on-primary-fixed": "#443700",
        "error-container": "#f95630",
        "primary-container": "#fad538",
        "tertiary-fixed": "#ff9655",
        "outline-variant": "#abadae",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#ebc729",
        "on-secondary-fixed-variant": "#004f9e",
        "surface-container": "#e6e8ea",
        "surface": "#f5f6f7",
        "primary-dim": "#5f4e00",
        "primary": "#6d5a00",
        "tertiary-fixed-dim": "#f6853b",
        "on-secondary": "#eff2ff",
        "on-tertiary": "#fff0e9",
        "on-error-container": "#520c00",
        "error": "#b02500",
        "tertiary-container": "#ff9655",
        "secondary-fixed": "#bcd2ff",
        "secondary": "#005ab2",
        "surface-variant": "#dadddf",
        "secondary-container": "#bcd2ff",
        "inverse-primary": "#fad538",
        "secondary-fixed-dim": "#a5c5ff",
        "surface-bright": "#f5f6f7",
        "on-surface": "#2c2f30",
        "on-primary-container": "#5a4a00",
        "on-error": "#ffefec",
        "inverse-surface": "#0c0f10",
        "on-primary-fixed-variant": "#655300",
        "on-primary": "#fff2ce",
        "surface-container-high": "#e0e3e4",
        "on-tertiary-fixed": "#2d0f00",
        "inverse-on-surface": "#9b9d9e",
        "error-dim": "#b92902",
        "tertiary": "#964300",
        "on-surface-variant": "#595c5d",
        "on-background": "#2c2f30",
        "outline": "#757778",
        "on-secondary-container": "#00468e",
        "on-tertiary-fixed-variant": "#612900",
        "surface-tint": "#6d5a00",
        "on-tertiary-container": "#532200",
        "background": "#f5f6f7",
        "surface-container-highest": "#dadddf",
        "surface-dim": "#d1d5d7",
        "primary-fixed": "#fad538",
        "on-secondary-fixed": "#00336b"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "2xl": "3rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Inter"],
        "label": ["Inter"]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
